apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: {{ include "var.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  forProvider:
    displayName: Crossplane-managed service account
