apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "var.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "var.labels" . | nindent 4 }}
  annotations:
    "iam.gke.io/gcp-service-account": {{ include "var.serviceAccountPrinciple" . }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
