apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  name: {{ include "var.serviceAccountName" . }}-workload-identity-user
spec:
  forProvider:
    member: serviceAccount:{{ .Values.gcpProjectId }}.svc.id.goog[{{ .Release.Namespace }}/{{ include "var.serviceAccountName" . }}]
    role: roles/iam.workloadIdentityUser
    serviceAccountIdRef:
      name: {{ include "var.serviceAccountName" . }}
